<a href="https://colab.research.google.com/github/umeshgurjar914042-creator/python-pandas-practice/blob/main/Copy_of_Untitled0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [40]:
print("ram ram ji ")

ram ram ji

In [41]:
import pandas as pd

data = {
    "फल": ["आम", "केला", "सेब", "अंगूर"],
    "कीमत": [80, 40, 120, 90],
    "मात्रा": [10, 25, 5, 8]
}

df = pd.DataFrame(data)
df

      फल  कीमत  मात्रा
0     आम    80      10
1   केला    40      25
2    सेब   120       5
3  अंगूर    90       8

In [42]:
# 1 से 10 तक के पहाड़े (Multiplication Tables)
for i in range(1, 11):
    print(f"--- {i} का पहाड़ा ---")
    for j in range(1, 11):
        print(f"{i} x {j} = {i * j}")
    print()  # प्रत्येक पहाड़े के बाद एक खाली लाइन

--- 1 का पहाड़ा ---
1 x 1 = 1
1 x 2 = 2
1 x 3 = 3
1 x 4 = 4
1 x 5 = 5
1 x 6 = 6
1 x 7 = 7
1 x 8 = 8
1 x 9 = 9
1 x 10 = 10

--- 2 का पहाड़ा ---
2 x 1 = 2
2 x 2 = 4
2 x 3 = 6
2 x 4 = 8
2 x 5 = 10
2 x 6 = 12
2 x 7 = 14
2 x 8 = 16
2 x 9 = 18
2 x 10 = 20

--- 3 का पहाड़ा ---
3 x 1 = 3
3 x 2 = 6
3 x 3 = 9
3 x 4 = 12
3 x 5 = 15
3 x 6 = 18
3 x 7 = 21
3 x 8 = 24
3 x 9 = 27
3 x 10 = 30

--- 4 का पहाड़ा ---
4 x 1 = 4
4 x 2 = 8
4 x 3 = 12
4 x 4 = 16
4 x 5 = 20
4 x 6 = 24
4 x 7 = 28
4 x 8 = 32
4 x 9 = 36
4 x 10 = 40

--- 5 का पहाड़ा ---
5 x 1 = 5
5 x 2 = 10
5 x 3 = 15
5 x 4 = 20
5 x 5 = 25
5 x 6 = 30
5 x 7 = 35
5 x 8 = 40
5 x 9 = 45
5 x 10 = 50

--- 6 का पहाड़ा ---
6 x 1 = 6
6 x 2 = 12
6 x 3 = 18
6 x 4 = 24
6 x 5 = 30
6 x 6 = 36
6 x 7 = 42
6 x 8 = 48
6 x 9 = 54
6 x 10 = 60

--- 7 का पहाड़ा ---
7 x 1 = 7
7 x 2 = 14
7 x 3 = 21
7 x 4 = 28
7 x 5 = 35
7 x 6 = 42
7 x 7 = 49
7 x 8 = 56
7 x 9 = 63
7 x 10 = 70

--- 8 का पहाड़ा ---
8 x 1 = 8
8 x 2 = 16
8 x 3 = 24
8 x 4 = 32
8 x 5 = 40
8 x 6 = 48
8 x 7 = 56
8 x 8 = 64
8 x 9 = 72
8 x 10 = 80

--- 9 का पहाड़ा ---
9 x 1 = 9
9 x 2 = 18
9 x 3 = 27
9 x 4 = 36
9 x 5 = 45
9 x 6 = 54
9 x 7 = 63
9 x 8 = 72
9 x 9 = 81
9 x 10 = 90

--- 10 का पहाड़ा ---
10 x 1 = 10
10 x 2 = 20
10 x 3 = 30
10 x 4 = 40
10 x 5 = 50
10 x 6 = 60
10 x 7 = 70
10 x 8 = 80
10 x 9 = 90
10 x 10 = 100

### 1. Integer (पूर्णांक संख्या)
जब हमें बिना दशमलव (decimal) वाले पूरे नंबर स्टोर करने होते हैं।

In [43]:
# उदाहरण 1: उम्र (Integer)
umar = 25
print("उम्र:", umar)
print("Data Type:", type(umar))

उम्र: 25
Data Type: <class 'int'>

### 2. Float (दशमलव संख्या)
जब हमें दशमलव वाले नंबर जैसे कि कीमत या तापमान स्टोर करना हो।

In [44]:
# उदाहरण 2: तापमान (Float)
tapman = 36.6
print("तापमान:", tapman)
print("Data Type:", type(tapman))

तापमान: 36.6
Data Type: <class 'float'>

### 3. String (टेक्स्ट/अक्षर)
जब हमें कोई नाम, वाक्य या शब्द स्टोर करना हो। इसे हमेशा सिंगल (' ') या डबल (" ") कोट्स के अंदर लिखा जाता है।

In [45]:
# उदाहरण 3: नाम (String)
naam = "राम"
print("नाम:", naam)
print("Data Type:", type(naam))

नाम: राम
Data Type: <class 'str'>

### 4. Boolean (सत्य या असत्य)
यह केवल दो ही मान (values) ले सकता है: `True` (हाँ/सही) या `False` (ना/गलत)।

In [46]:
# उदाहरण 4: क्या यूज़र लॉग इन है? (Boolean)
is_logged_in = True
print("लॉग इन स्थिति:", is_logged_in)
print("Data Type:", type(is_logged_in))

लॉग इन स्थिति: True
Data Type: <class 'bool'>

### 5. List (चीज़ों की सूची)
जब हमें एक ही variable में एक से ज़्यादा चीज़ें एक क्रम में रखनी हों। इसे `[]` ब्रैकेट्स में लिखा जाता है।

In [47]:
import pandas as pd

# डेटा तैयार करना
data = {
    "फल": ["आम", "केला", "सेब", "अंगूर"],
    "कीमत": [80, 40, 120, 90],
    "मात्रा": [10, 25, 5, 8]
}

# DataFrame बनाना
df = pd.DataFrame(data)

# 'कुल' कॉलम बनाना (कीमत * मात्रा)
df["कुल"] = df["कीमत"] * df["मात्रा"]

# DataFrame प्रिंट करना
print("--- फलों का डेटाफ़्रेम ---")
print(df)
print()

# कुल बिक्री का जोड़
total_sales = df["कुल"].sum()
print("कुल बिक्री का जोड़ (Total Sales):", total_sales)

--- फलों का डेटाफ़्रेम ---
      फल  कीमत  मात्रा   कुल
0     आम    80      10   800
1   केला    40      25  1000
2    सेब   120       5   600
3  अंगूर    90       8   720

कुल बिक्री का जोड़ (Total Sales): 3120

In [48]:
# 50 से ज़्यादा कीमत वाले फलों को फ़िल्टर करना
mehnge_fal = df[df["कीमत"] > 50]

print("--- 50 से ज़्यादा कीमत वाले फल ---")
display(mehnge_fal)

--- 50 से ज़्यादा कीमत वाले फल ---

      फल  कीमत  मात्रा  कुल
0     आम    80      10  800
2    सेब   120       5  600
3  अंगूर    90       8  720

In [49]:
import pandas as pd
import random

# नकली डेटा (Synthetic Data) के लिए विकल्प
products = ["लैपटॉप", "मोबाइल", "हेडफोन", "स्मार्टवॉच", "टैबलेट"]
cities = ["दिल्ली", "मुंबई", "बेंगलुरु", "कोलकाता", "चेन्नई"]

# 10 पंक्तियों का डेटा तैयार करना
random.seed(42)  # परिणाम को सुसंगत रखने के लिए
sales_data = {
    "प्रोडक्ट": [random.choice(products) for _ in range(10)],
    "शहर": [random.choice(cities) for _ in range(10)],
    "कीमत": [random.randint(1000, 50000) for _ in range(10)],
    "मात्रा": [random.randint(1, 5) for _ in range(10)]
}

# DataFrame बनाना
sales_df = pd.DataFrame(sales_data)

# sales.csv नाम से सेव करना
sales_df.to_csv("sales.csv", index=False)

print("--- sales.csv सफलतापूर्वक बना दिया गया है ---")
display(sales_df)

--- sales.csv सफलतापूर्वक बना दिया गया है ---

  प्रोडक्ट      शहर   कीमत  मात्रा
0   लैपटॉप  कोलकाता  14031       1
1   लैपटॉप   दिल्ली  47925       2
2   हेडफोन   दिल्ली  43590       4
3   मोबाइल   दिल्ली  46962       3
4   मोबाइल    मुंबई  36713       3
5   मोबाइल    मुंबई  28493       2
6   लैपटॉप   चेन्नई  15446       2
7   टैबलेट   चेन्नई  30439       3
8   लैपटॉप   दिल्ली  39618       1
9   टैबलेट   चेन्नई  19231       1

In [50]:
# sales.csv फ़ाइल को लोड करना
loaded_df = pd.read_csv("sales.csv")

# पहली 5 पंक्तियाँ दिखाना
print("--- sales.csv की पहली 5 पंक्तियाँ ---")
display(loaded_df.head(5))

--- sales.csv की पहली 5 पंक्तियाँ ---

  प्रोडक्ट      शहर   कीमत  मात्रा
0   लैपटॉप  कोलकाता  14031       1
1   लैपटॉप   दिल्ली  47925       2
2   हेडफोन   दिल्ली  43590       4
3   मोबाइल   दिल्ली  46962       3
4   मोबाइल    मुंबई  36713       3

In [51]:
# DataFrame की संरचना और डेटा टाइप्स की जानकारी (info)
print("--- DataFrame की मूलभूत जानकारी (Info) ---")
loaded_df.info()

print("\n" + "="*50 + "\n")

# DataFrame का सांख्यिकीय विवरण (describe)
print("--- DataFrame का सांख्यिकीय विवरण (Describe) ---")
display(loaded_df.describe())

--- DataFrame की मूलभूत जानकारी (Info) ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   प्रोडक्ट  10 non-null     object
 1   शहर       10 non-null     object
 2   कीमत      10 non-null     int64
 3   मात्रा    10 non-null     int64
dtypes: int64(2), object(2)
memory usage: 452.0+ bytes

==================================================

--- DataFrame का सांख्यिकीय विवरण (Describe) ---

               कीमत     मात्रा
count     10.000000  10.000000
mean   32244.800000   2.200000
std    12763.425174   1.032796
min    14031.000000   1.000000
25%    21546.500000   1.250000
50%    33576.000000   2.000000
75%    42597.000000   3.000000
max    47925.000000   4.000000

In [52]:
# हर रिकॉर्ड के लिए कुल बिक्री (कीमत * मात्रा) की गणना करना
loaded_df["कुल बिक्री"] = loaded_df["कीमत"] * loaded_df["मात्रा"]

# शहर के अनुसार कुल बिक्री का योग निकालना
city_sales = loaded_df.groupby("शहर")["कुल बिक्री"].sum().reset_index()

# कुल बिक्री के आधार पर अवरोही क्रम (descending order) में सॉर्ट करना
city_sales = city_sales.sort_values(by="कुल बिक्री", ascending=False)

print("--- शहर के अनुसार कुल बिक्री ---")
display(city_sales)

# सबसे ज़्यादा बिक्री वाला शहर
top_city = city_sales.iloc[0]
print(f"\nसबसे ज़्यादा बिक्री वाला शहर: {top_city['शहर']} ({top_city['कुल बिक्री']} रुपए)")

--- शहर के अनुसार कुल बिक्री ---

       शहर  कुल बिक्री
2   दिल्ली      450714
3    मुंबई      167125
1   चेन्नई      141440
0  कोलकाता       14031

सबसे ज़्यादा बिक्री वाला शहर: दिल्ली (450714 रुपए)